// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8pgJVB8RkrAt5f9HTyTeXZNdIBc4ycfg',
    appId: '1:582441247897:web:40cf5326cabbba8eff0408',
    messagingSenderId: '582441247897',
    projectId: 'report1-4a414',
    authDomain: 'report1-4a414.firebaseapp.com',
    storageBucket: 'report1-4a414.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBcVnOBQGXo2QOwgLF4Qa_Mff-ovu3vGQ',
    appId: '1:582441247897:android:ae3fa70333999753ff0408',
    messagingSenderId: '582441247897',
    projectId: 'report1-4a414',
    storageBucket: 'report1-4a414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzq2ozWBHxtT8uFw-u67cxCG2poauKTZs',
    appId: '1:582441247897:ios:14e8ae81fde30733ff0408',
    messagingSenderId: '582441247897',
    projectId: 'report1-4a414',
    storageBucket: 'report1-4a414.appspot.com',
    iosClientId: '582441247897-a4jurq4nt8hfl0mrv9re61dl36g4prjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseReport1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzq2ozWBHxtT8uFw-u67cxCG2poauKTZs',
    appId: '1:582441247897:ios:14e8ae81fde30733ff0408',
    messagingSenderId: '582441247897',
    projectId: 'report1-4a414',
    storageBucket: 'report1-4a414.appspot.com',
    iosClientId: '582441247897-a4jurq4nt8hfl0mrv9re61dl36g4prjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseReport1',
  );
}
